version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  app:
    container_name: app
    build: app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - 8002:8002
