version: "3.9"
services:
  static-server:
    build: ./staticServer
    volumes:
      - ./static:/images
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data
    ports:
      - 8080:8080
