version: '3.1'

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: l8_db
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rest-app:
    container_name: rest-app
    build: rest-app
    environment:
      - MYSQL_HOST=db
    ports:
      - 3000:3000
