version: '3'

services:
  beanstalkd:
    image: schickling/beanstalkd
    container_name: beanstalkd
    restart: always
    ports:
      - 11300:11300
  redis_aof:
    image: 'bitnami/redis:latest'
    ports:
      - 7000:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-aof.conf:/opt/bitnami/redis/mounted-etc/redis.conf

  redis_rdb:
    image: 'bitnami/redis:latest'
    ports:
      - 7001:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_AOF_ENABLED=no
