version: '3.1'

services:
  redis-primary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis-data/redis-primary:/bitnami/redis/data'
      - './redis-primary.conf:/opt/bitnami/redis/mounted-etc/redis.conf'

  redis-secondary:
    image: docker.io/bitnami/redis:6.2
    ports:
      - '6379'
    depends_on:
      - redis-primary
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './redis-secondary.conf:/opt/bitnami/redis/mounted-etc/redis.conf'
