version: '3.8'

services:

  mysql-m:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql-m-conf.d:/etc/mysql/conf.d
      - ./dumps:/opt/data/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mydb

  mysql-s-1:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql-s-1-conf.d:/etc/mysql/conf.d
      - ./dumps:/opt/data/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mydb

  mysql-s-2:
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./mysql-s-2-conf.d:/etc/mysql/conf.d
      - ./dumps:/opt/data/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
