version: '3.7'

services:
  nginx:
    image: nginx:1.21.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080

  app:
    build: ./app
    ports:
      - 5000
    stop_signal: SIGINT

  kali:
    image: kalilinux/kali-rolling
    # on clean startup: apt update && apt -y install kali-linux-headless
    command: sleep infinity
