version: '3.7'

services:
  nginx:
    cpus: 0.1
    mem_limit: 64m
    image: nginx:1.21.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080

  app:
    build: ./app
    ports:
      - 5000
    stop_signal: SIGINT

  kali:
    build: ./kali
