version: '3.8'

services:
  postgresql-b:
    image: postgres:14.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_db

  postgresql-b1:
    image: postgres:14.1
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_db

  postgresql-b2:
    image: postgres:14.1
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_db
